{% set name = "pymongo" %}
{% set version = "3.5.1" %}

package:
  name: pymongo
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  fn: pymongo-{{ version }}.tar.gz
  sha256: e820d93414f3bec1fa456c84afbd4af1b43ff41366321619db74e6bc065d6924

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    # Only for testing
    - mongodb

  run:
    - python

test:
  imports:
    - bson
    - gridfs
    - pymongo

about:
  home: https://github.com/mongodb/mongo-python-driver
  license: Apache 2.0
  license_file: LICENSE
  summary: Python driver for MongoDB
  description: |
    PyMongo is a Python distribution containing tools for working with MongoDB
    and is the recommended way to work with MongoDB from Python.
  doc_url: http://api.mongodb.org/python
  doc_source_url: https://github.com/mongodb/mongo-python-driver/blob/master/doc/index.rst
  dev_url: https://github.com/mongodb/mongo-python-driver

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - jakirkham
    - tacaswell
